<?xml version="1.0" encoding="utf-8"?>
<Database Name="ClassManage" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=222.16.131.157;Initial Catalog=ClassManage;Persist Security Info=True;User ID=sa" SettingsObjectName="ClassManage.Properties.Settings" SettingsPropertyName="ClassManageConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.class" Member="class">
    <Type Name="class">
      <Column Name="Class_id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Class_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Class_college" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Class_teacherid" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="User_id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="User_password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="User_power" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.course" Member="course">
    <Type Name="course">
      <Column Name="Course_id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Course_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Course_period" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Course_credit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Course_kind" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Course_descible" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.exam" Member="exam">
    <Type Name="exam">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="course_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="exam_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="exam_address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.score" Member="score">
    <Type Name="score">
      <Column Name="Student_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Course_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Course_score" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.student" Member="student">
    <Type Name="student">
      <Column Name="Student_id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Student_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Student_sex" Type="System.String" DbType="Char(50) NOT NULL" CanBeNull="false" />
      <Column Name="Student_nation" Type="System.String" DbType="Char(50) NOT NULL" CanBeNull="false" />
      <Column Name="Student_birthday" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Student_classid" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Student_home" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="School_location" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Student_college" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Student_specialty" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="School_system" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Entry_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Student_grade" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.sutdent_course" Member="sutdent_course">
    <Type Name="sutdent_course">
      <Column Name="Student_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Course_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.teacher" Member="teacher">
    <Type Name="teacher">
      <Column Name="Teacher_id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Teacher_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Teacher_college" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.teacher_course" Member="teacher_course">
    <Type Name="teacher_course">
      <Column Name="Teacher_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Course_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Class_id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Reward_Punish" Member="Reward_Punish">
    <Type Name="Reward_Punish">
      <Column Name="studengID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="rewards" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="punishments" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="xuenian" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.School_fee" Member="School_fee">
    <Type Name="School_fee">
      <Column Name="Xuenian" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="Yingjiaoxuefei" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Yijiaoxuefei" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Qianjiaoxuefei" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Yingjiaozhusufei" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Yijiaozhusufei" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Qianjiaozhusufei" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="studentID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>