#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4971
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassManage
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="ClassManage")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertclass(@class instance);
    partial void Updateclass(@class instance);
    partial void Deleteclass(@class instance);
    partial void InsertUsers(Users instance);
    partial void UpdateUsers(Users instance);
    partial void DeleteUsers(Users instance);
    partial void Insertcourse(course instance);
    partial void Updatecourse(course instance);
    partial void Deletecourse(course instance);
    partial void Insertexam(exam instance);
    partial void Updateexam(exam instance);
    partial void Deleteexam(exam instance);
    partial void Insertscore(score instance);
    partial void Updatescore(score instance);
    partial void Deletescore(score instance);
    partial void Insertstudent(student instance);
    partial void Updatestudent(student instance);
    partial void Deletestudent(student instance);
    partial void Insertsutdent_course(sutdent_course instance);
    partial void Updatesutdent_course(sutdent_course instance);
    partial void Deletesutdent_course(sutdent_course instance);
    partial void Insertteacher(teacher instance);
    partial void Updateteacher(teacher instance);
    partial void Deleteteacher(teacher instance);
    partial void Insertteacher_course(teacher_course instance);
    partial void Updateteacher_course(teacher_course instance);
    partial void Deleteteacher_course(teacher_course instance);
    partial void InsertReward_Punish(Reward_Punish instance);
    partial void UpdateReward_Punish(Reward_Punish instance);
    partial void DeleteReward_Punish(Reward_Punish instance);
    partial void InsertSchool_fee(School_fee instance);
    partial void UpdateSchool_fee(School_fee instance);
    partial void DeleteSchool_fee(School_fee instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ClassManage.Properties.Settings.Default.ClassManageConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<@class> @class
		{
			get
			{
				return this.GetTable<@class>();
			}
		}
		
		public System.Data.Linq.Table<Users> Users
		{
			get
			{
				return this.GetTable<Users>();
			}
		}
		
		public System.Data.Linq.Table<course> course
		{
			get
			{
				return this.GetTable<course>();
			}
		}
		
		public System.Data.Linq.Table<exam> exam
		{
			get
			{
				return this.GetTable<exam>();
			}
		}
		
		public System.Data.Linq.Table<score> score
		{
			get
			{
				return this.GetTable<score>();
			}
		}
		
		public System.Data.Linq.Table<student> student
		{
			get
			{
				return this.GetTable<student>();
			}
		}
		
		public System.Data.Linq.Table<sutdent_course> sutdent_course
		{
			get
			{
				return this.GetTable<sutdent_course>();
			}
		}
		
		public System.Data.Linq.Table<teacher> teacher
		{
			get
			{
				return this.GetTable<teacher>();
			}
		}
		
		public System.Data.Linq.Table<teacher_course> teacher_course
		{
			get
			{
				return this.GetTable<teacher_course>();
			}
		}
		
		public System.Data.Linq.Table<Reward_Punish> Reward_Punish
		{
			get
			{
				return this.GetTable<Reward_Punish>();
			}
		}
		
		public System.Data.Linq.Table<School_fee> School_fee
		{
			get
			{
				return this.GetTable<School_fee>();
			}
		}
	}
	
	[Table(Name="dbo.class")]
	public partial class @class : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Class_id;
		
		private string _Class_name;
		
		private string _Class_college;
		
		private string _Class_teacherid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnClass_idChanging(string value);
    partial void OnClass_idChanged();
    partial void OnClass_nameChanging(string value);
    partial void OnClass_nameChanged();
    partial void OnClass_collegeChanging(string value);
    partial void OnClass_collegeChanged();
    partial void OnClass_teacheridChanging(string value);
    partial void OnClass_teacheridChanged();
    #endregion
		
		public @class()
		{
			OnCreated();
		}
		
		[Column(Storage="_Class_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Class_id
		{
			get
			{
				return this._Class_id;
			}
			set
			{
				if ((this._Class_id != value))
				{
					this.OnClass_idChanging(value);
					this.SendPropertyChanging();
					this._Class_id = value;
					this.SendPropertyChanged("Class_id");
					this.OnClass_idChanged();
				}
			}
		}
		
		[Column(Storage="_Class_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Class_name
		{
			get
			{
				return this._Class_name;
			}
			set
			{
				if ((this._Class_name != value))
				{
					this.OnClass_nameChanging(value);
					this.SendPropertyChanging();
					this._Class_name = value;
					this.SendPropertyChanged("Class_name");
					this.OnClass_nameChanged();
				}
			}
		}
		
		[Column(Storage="_Class_college", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Class_college
		{
			get
			{
				return this._Class_college;
			}
			set
			{
				if ((this._Class_college != value))
				{
					this.OnClass_collegeChanging(value);
					this.SendPropertyChanging();
					this._Class_college = value;
					this.SendPropertyChanged("Class_college");
					this.OnClass_collegeChanged();
				}
			}
		}
		
		[Column(Storage="_Class_teacherid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Class_teacherid
		{
			get
			{
				return this._Class_teacherid;
			}
			set
			{
				if ((this._Class_teacherid != value))
				{
					this.OnClass_teacheridChanging(value);
					this.SendPropertyChanging();
					this._Class_teacherid = value;
					this.SendPropertyChanged("Class_teacherid");
					this.OnClass_teacheridChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Users")]
	public partial class Users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _User_id;
		
		private string _User_password;
		
		private int _User_power;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_idChanging(string value);
    partial void OnUser_idChanged();
    partial void OnUser_passwordChanging(string value);
    partial void OnUser_passwordChanged();
    partial void OnUser_powerChanging(int value);
    partial void OnUser_powerChanged();
    #endregion
		
		public Users()
		{
			OnCreated();
		}
		
		[Column(Storage="_User_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string User_id
		{
			get
			{
				return this._User_id;
			}
			set
			{
				if ((this._User_id != value))
				{
					this.OnUser_idChanging(value);
					this.SendPropertyChanging();
					this._User_id = value;
					this.SendPropertyChanged("User_id");
					this.OnUser_idChanged();
				}
			}
		}
		
		[Column(Storage="_User_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string User_password
		{
			get
			{
				return this._User_password;
			}
			set
			{
				if ((this._User_password != value))
				{
					this.OnUser_passwordChanging(value);
					this.SendPropertyChanging();
					this._User_password = value;
					this.SendPropertyChanged("User_password");
					this.OnUser_passwordChanged();
				}
			}
		}
		
		[Column(Storage="_User_power", DbType="Int NOT NULL")]
		public int User_power
		{
			get
			{
				return this._User_power;
			}
			set
			{
				if ((this._User_power != value))
				{
					this.OnUser_powerChanging(value);
					this.SendPropertyChanging();
					this._User_power = value;
					this.SendPropertyChanged("User_power");
					this.OnUser_powerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.course")]
	public partial class course : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Course_id;
		
		private string _Course_name;
		
		private int _Course_period;
		
		private int _Course_credit;
		
		private string _Course_kind;
		
		private string _Course_descible;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCourse_idChanging(string value);
    partial void OnCourse_idChanged();
    partial void OnCourse_nameChanging(string value);
    partial void OnCourse_nameChanged();
    partial void OnCourse_periodChanging(int value);
    partial void OnCourse_periodChanged();
    partial void OnCourse_creditChanging(int value);
    partial void OnCourse_creditChanged();
    partial void OnCourse_kindChanging(string value);
    partial void OnCourse_kindChanged();
    partial void OnCourse_descibleChanging(string value);
    partial void OnCourse_descibleChanged();
    #endregion
		
		public course()
		{
			OnCreated();
		}
		
		[Column(Storage="_Course_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Course_id
		{
			get
			{
				return this._Course_id;
			}
			set
			{
				if ((this._Course_id != value))
				{
					this.OnCourse_idChanging(value);
					this.SendPropertyChanging();
					this._Course_id = value;
					this.SendPropertyChanged("Course_id");
					this.OnCourse_idChanged();
				}
			}
		}
		
		[Column(Storage="_Course_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Course_name
		{
			get
			{
				return this._Course_name;
			}
			set
			{
				if ((this._Course_name != value))
				{
					this.OnCourse_nameChanging(value);
					this.SendPropertyChanging();
					this._Course_name = value;
					this.SendPropertyChanged("Course_name");
					this.OnCourse_nameChanged();
				}
			}
		}
		
		[Column(Storage="_Course_period", DbType="Int NOT NULL")]
		public int Course_period
		{
			get
			{
				return this._Course_period;
			}
			set
			{
				if ((this._Course_period != value))
				{
					this.OnCourse_periodChanging(value);
					this.SendPropertyChanging();
					this._Course_period = value;
					this.SendPropertyChanged("Course_period");
					this.OnCourse_periodChanged();
				}
			}
		}
		
		[Column(Storage="_Course_credit", DbType="Int NOT NULL")]
		public int Course_credit
		{
			get
			{
				return this._Course_credit;
			}
			set
			{
				if ((this._Course_credit != value))
				{
					this.OnCourse_creditChanging(value);
					this.SendPropertyChanging();
					this._Course_credit = value;
					this.SendPropertyChanged("Course_credit");
					this.OnCourse_creditChanged();
				}
			}
		}
		
		[Column(Storage="_Course_kind", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Course_kind
		{
			get
			{
				return this._Course_kind;
			}
			set
			{
				if ((this._Course_kind != value))
				{
					this.OnCourse_kindChanging(value);
					this.SendPropertyChanging();
					this._Course_kind = value;
					this.SendPropertyChanged("Course_kind");
					this.OnCourse_kindChanged();
				}
			}
		}
		
		[Column(Storage="_Course_descible", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Course_descible
		{
			get
			{
				return this._Course_descible;
			}
			set
			{
				if ((this._Course_descible != value))
				{
					this.OnCourse_descibleChanging(value);
					this.SendPropertyChanging();
					this._Course_descible = value;
					this.SendPropertyChanged("Course_descible");
					this.OnCourse_descibleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.exam")]
	public partial class exam : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _course_id;
		
		private System.Nullable<System.DateTime> _exam_time;
		
		private string _exam_address;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void Oncourse_idChanging(string value);
    partial void Oncourse_idChanged();
    partial void Onexam_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onexam_timeChanged();
    partial void Onexam_addressChanging(string value);
    partial void Onexam_addressChanged();
    #endregion
		
		public exam()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_course_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string course_id
		{
			get
			{
				return this._course_id;
			}
			set
			{
				if ((this._course_id != value))
				{
					this.Oncourse_idChanging(value);
					this.SendPropertyChanging();
					this._course_id = value;
					this.SendPropertyChanged("course_id");
					this.Oncourse_idChanged();
				}
			}
		}
		
		[Column(Storage="_exam_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> exam_time
		{
			get
			{
				return this._exam_time;
			}
			set
			{
				if ((this._exam_time != value))
				{
					this.Onexam_timeChanging(value);
					this.SendPropertyChanging();
					this._exam_time = value;
					this.SendPropertyChanged("exam_time");
					this.Onexam_timeChanged();
				}
			}
		}
		
		[Column(Storage="_exam_address", DbType="NVarChar(50)")]
		public string exam_address
		{
			get
			{
				return this._exam_address;
			}
			set
			{
				if ((this._exam_address != value))
				{
					this.Onexam_addressChanging(value);
					this.SendPropertyChanging();
					this._exam_address = value;
					this.SendPropertyChanged("exam_address");
					this.Onexam_addressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.score")]
	public partial class score : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Student_id;
		
		private string _Course_id;
		
		private int _Course_score;
		
		private string _id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStudent_idChanging(string value);
    partial void OnStudent_idChanged();
    partial void OnCourse_idChanging(string value);
    partial void OnCourse_idChanged();
    partial void OnCourse_scoreChanging(int value);
    partial void OnCourse_scoreChanged();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    #endregion
		
		public score()
		{
			OnCreated();
		}
		
		[Column(Storage="_Student_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Student_id
		{
			get
			{
				return this._Student_id;
			}
			set
			{
				if ((this._Student_id != value))
				{
					this.OnStudent_idChanging(value);
					this.SendPropertyChanging();
					this._Student_id = value;
					this.SendPropertyChanged("Student_id");
					this.OnStudent_idChanged();
				}
			}
		}
		
		[Column(Storage="_Course_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Course_id
		{
			get
			{
				return this._Course_id;
			}
			set
			{
				if ((this._Course_id != value))
				{
					this.OnCourse_idChanging(value);
					this.SendPropertyChanging();
					this._Course_id = value;
					this.SendPropertyChanged("Course_id");
					this.OnCourse_idChanged();
				}
			}
		}
		
		[Column(Storage="_Course_score", DbType="Int NOT NULL")]
		public int Course_score
		{
			get
			{
				return this._Course_score;
			}
			set
			{
				if ((this._Course_score != value))
				{
					this.OnCourse_scoreChanging(value);
					this.SendPropertyChanging();
					this._Course_score = value;
					this.SendPropertyChanged("Course_score");
					this.OnCourse_scoreChanged();
				}
			}
		}
		
		[Column(Storage="_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.student")]
	public partial class student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Student_id;
		
		private string _Student_name;
		
		private string _Student_sex;
		
		private string _Student_nation;
		
		private System.DateTime _Student_birthday;
		
		private string _Student_classid;
		
		private string _Student_home;
		
		private string _School_location;
		
		private string _Student_college;
		
		private string _Student_specialty;
		
		private int _School_system;
		
		private System.DateTime _Entry_date;
		
		private int _Student_grade;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStudent_idChanging(string value);
    partial void OnStudent_idChanged();
    partial void OnStudent_nameChanging(string value);
    partial void OnStudent_nameChanged();
    partial void OnStudent_sexChanging(string value);
    partial void OnStudent_sexChanged();
    partial void OnStudent_nationChanging(string value);
    partial void OnStudent_nationChanged();
    partial void OnStudent_birthdayChanging(System.DateTime value);
    partial void OnStudent_birthdayChanged();
    partial void OnStudent_classidChanging(string value);
    partial void OnStudent_classidChanged();
    partial void OnStudent_homeChanging(string value);
    partial void OnStudent_homeChanged();
    partial void OnSchool_locationChanging(string value);
    partial void OnSchool_locationChanged();
    partial void OnStudent_collegeChanging(string value);
    partial void OnStudent_collegeChanged();
    partial void OnStudent_specialtyChanging(string value);
    partial void OnStudent_specialtyChanged();
    partial void OnSchool_systemChanging(int value);
    partial void OnSchool_systemChanged();
    partial void OnEntry_dateChanging(System.DateTime value);
    partial void OnEntry_dateChanged();
    partial void OnStudent_gradeChanging(int value);
    partial void OnStudent_gradeChanged();
    #endregion
		
		public student()
		{
			OnCreated();
		}
		
		[Column(Storage="_Student_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Student_id
		{
			get
			{
				return this._Student_id;
			}
			set
			{
				if ((this._Student_id != value))
				{
					this.OnStudent_idChanging(value);
					this.SendPropertyChanging();
					this._Student_id = value;
					this.SendPropertyChanged("Student_id");
					this.OnStudent_idChanged();
				}
			}
		}
		
		[Column(Storage="_Student_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Student_name
		{
			get
			{
				return this._Student_name;
			}
			set
			{
				if ((this._Student_name != value))
				{
					this.OnStudent_nameChanging(value);
					this.SendPropertyChanging();
					this._Student_name = value;
					this.SendPropertyChanged("Student_name");
					this.OnStudent_nameChanged();
				}
			}
		}
		
		[Column(Storage="_Student_sex", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string Student_sex
		{
			get
			{
				return this._Student_sex;
			}
			set
			{
				if ((this._Student_sex != value))
				{
					this.OnStudent_sexChanging(value);
					this.SendPropertyChanging();
					this._Student_sex = value;
					this.SendPropertyChanged("Student_sex");
					this.OnStudent_sexChanged();
				}
			}
		}
		
		[Column(Storage="_Student_nation", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string Student_nation
		{
			get
			{
				return this._Student_nation;
			}
			set
			{
				if ((this._Student_nation != value))
				{
					this.OnStudent_nationChanging(value);
					this.SendPropertyChanging();
					this._Student_nation = value;
					this.SendPropertyChanged("Student_nation");
					this.OnStudent_nationChanged();
				}
			}
		}
		
		[Column(Storage="_Student_birthday", DbType="DateTime NOT NULL")]
		public System.DateTime Student_birthday
		{
			get
			{
				return this._Student_birthday;
			}
			set
			{
				if ((this._Student_birthday != value))
				{
					this.OnStudent_birthdayChanging(value);
					this.SendPropertyChanging();
					this._Student_birthday = value;
					this.SendPropertyChanged("Student_birthday");
					this.OnStudent_birthdayChanged();
				}
			}
		}
		
		[Column(Storage="_Student_classid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Student_classid
		{
			get
			{
				return this._Student_classid;
			}
			set
			{
				if ((this._Student_classid != value))
				{
					this.OnStudent_classidChanging(value);
					this.SendPropertyChanging();
					this._Student_classid = value;
					this.SendPropertyChanged("Student_classid");
					this.OnStudent_classidChanged();
				}
			}
		}
		
		[Column(Storage="_Student_home", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Student_home
		{
			get
			{
				return this._Student_home;
			}
			set
			{
				if ((this._Student_home != value))
				{
					this.OnStudent_homeChanging(value);
					this.SendPropertyChanging();
					this._Student_home = value;
					this.SendPropertyChanged("Student_home");
					this.OnStudent_homeChanged();
				}
			}
		}
		
		[Column(Storage="_School_location", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string School_location
		{
			get
			{
				return this._School_location;
			}
			set
			{
				if ((this._School_location != value))
				{
					this.OnSchool_locationChanging(value);
					this.SendPropertyChanging();
					this._School_location = value;
					this.SendPropertyChanged("School_location");
					this.OnSchool_locationChanged();
				}
			}
		}
		
		[Column(Storage="_Student_college", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Student_college
		{
			get
			{
				return this._Student_college;
			}
			set
			{
				if ((this._Student_college != value))
				{
					this.OnStudent_collegeChanging(value);
					this.SendPropertyChanging();
					this._Student_college = value;
					this.SendPropertyChanged("Student_college");
					this.OnStudent_collegeChanged();
				}
			}
		}
		
		[Column(Storage="_Student_specialty", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Student_specialty
		{
			get
			{
				return this._Student_specialty;
			}
			set
			{
				if ((this._Student_specialty != value))
				{
					this.OnStudent_specialtyChanging(value);
					this.SendPropertyChanging();
					this._Student_specialty = value;
					this.SendPropertyChanged("Student_specialty");
					this.OnStudent_specialtyChanged();
				}
			}
		}
		
		[Column(Storage="_School_system", DbType="Int NOT NULL")]
		public int School_system
		{
			get
			{
				return this._School_system;
			}
			set
			{
				if ((this._School_system != value))
				{
					this.OnSchool_systemChanging(value);
					this.SendPropertyChanging();
					this._School_system = value;
					this.SendPropertyChanged("School_system");
					this.OnSchool_systemChanged();
				}
			}
		}
		
		[Column(Storage="_Entry_date", DbType="DateTime NOT NULL")]
		public System.DateTime Entry_date
		{
			get
			{
				return this._Entry_date;
			}
			set
			{
				if ((this._Entry_date != value))
				{
					this.OnEntry_dateChanging(value);
					this.SendPropertyChanging();
					this._Entry_date = value;
					this.SendPropertyChanged("Entry_date");
					this.OnEntry_dateChanged();
				}
			}
		}
		
		[Column(Storage="_Student_grade", DbType="Int NOT NULL")]
		public int Student_grade
		{
			get
			{
				return this._Student_grade;
			}
			set
			{
				if ((this._Student_grade != value))
				{
					this.OnStudent_gradeChanging(value);
					this.SendPropertyChanging();
					this._Student_grade = value;
					this.SendPropertyChanged("Student_grade");
					this.OnStudent_gradeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.sutdent_course")]
	public partial class sutdent_course : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Student_id;
		
		private string _Course_id;
		
		private string _id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStudent_idChanging(string value);
    partial void OnStudent_idChanged();
    partial void OnCourse_idChanging(string value);
    partial void OnCourse_idChanged();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    #endregion
		
		public sutdent_course()
		{
			OnCreated();
		}
		
		[Column(Storage="_Student_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Student_id
		{
			get
			{
				return this._Student_id;
			}
			set
			{
				if ((this._Student_id != value))
				{
					this.OnStudent_idChanging(value);
					this.SendPropertyChanging();
					this._Student_id = value;
					this.SendPropertyChanged("Student_id");
					this.OnStudent_idChanged();
				}
			}
		}
		
		[Column(Storage="_Course_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Course_id
		{
			get
			{
				return this._Course_id;
			}
			set
			{
				if ((this._Course_id != value))
				{
					this.OnCourse_idChanging(value);
					this.SendPropertyChanging();
					this._Course_id = value;
					this.SendPropertyChanged("Course_id");
					this.OnCourse_idChanged();
				}
			}
		}
		
		[Column(Storage="_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.teacher")]
	public partial class teacher : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Teacher_id;
		
		private string _Teacher_name;
		
		private string _Teacher_college;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTeacher_idChanging(string value);
    partial void OnTeacher_idChanged();
    partial void OnTeacher_nameChanging(string value);
    partial void OnTeacher_nameChanged();
    partial void OnTeacher_collegeChanging(string value);
    partial void OnTeacher_collegeChanged();
    #endregion
		
		public teacher()
		{
			OnCreated();
		}
		
		[Column(Storage="_Teacher_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Teacher_id
		{
			get
			{
				return this._Teacher_id;
			}
			set
			{
				if ((this._Teacher_id != value))
				{
					this.OnTeacher_idChanging(value);
					this.SendPropertyChanging();
					this._Teacher_id = value;
					this.SendPropertyChanged("Teacher_id");
					this.OnTeacher_idChanged();
				}
			}
		}
		
		[Column(Storage="_Teacher_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Teacher_name
		{
			get
			{
				return this._Teacher_name;
			}
			set
			{
				if ((this._Teacher_name != value))
				{
					this.OnTeacher_nameChanging(value);
					this.SendPropertyChanging();
					this._Teacher_name = value;
					this.SendPropertyChanged("Teacher_name");
					this.OnTeacher_nameChanged();
				}
			}
		}
		
		[Column(Storage="_Teacher_college", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Teacher_college
		{
			get
			{
				return this._Teacher_college;
			}
			set
			{
				if ((this._Teacher_college != value))
				{
					this.OnTeacher_collegeChanging(value);
					this.SendPropertyChanging();
					this._Teacher_college = value;
					this.SendPropertyChanged("Teacher_college");
					this.OnTeacher_collegeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.teacher_course")]
	public partial class teacher_course : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Teacher_id;
		
		private string _Course_id;
		
		private string _Class_id;
		
		private string _id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTeacher_idChanging(string value);
    partial void OnTeacher_idChanged();
    partial void OnCourse_idChanging(string value);
    partial void OnCourse_idChanged();
    partial void OnClass_idChanging(string value);
    partial void OnClass_idChanged();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    #endregion
		
		public teacher_course()
		{
			OnCreated();
		}
		
		[Column(Storage="_Teacher_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Teacher_id
		{
			get
			{
				return this._Teacher_id;
			}
			set
			{
				if ((this._Teacher_id != value))
				{
					this.OnTeacher_idChanging(value);
					this.SendPropertyChanging();
					this._Teacher_id = value;
					this.SendPropertyChanged("Teacher_id");
					this.OnTeacher_idChanged();
				}
			}
		}
		
		[Column(Storage="_Course_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Course_id
		{
			get
			{
				return this._Course_id;
			}
			set
			{
				if ((this._Course_id != value))
				{
					this.OnCourse_idChanging(value);
					this.SendPropertyChanging();
					this._Course_id = value;
					this.SendPropertyChanged("Course_id");
					this.OnCourse_idChanged();
				}
			}
		}
		
		[Column(Storage="_Class_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Class_id
		{
			get
			{
				return this._Class_id;
			}
			set
			{
				if ((this._Class_id != value))
				{
					this.OnClass_idChanging(value);
					this.SendPropertyChanging();
					this._Class_id = value;
					this.SendPropertyChanged("Class_id");
					this.OnClass_idChanged();
				}
			}
		}
		
		[Column(Storage="_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Reward_Punish")]
	public partial class Reward_Punish : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _studengID;
		
		private string _rewards;
		
		private string _punishments;
		
		private string _xuenian;
		
		private string _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstudengIDChanging(string value);
    partial void OnstudengIDChanged();
    partial void OnrewardsChanging(string value);
    partial void OnrewardsChanged();
    partial void OnpunishmentsChanging(string value);
    partial void OnpunishmentsChanged();
    partial void OnxuenianChanging(string value);
    partial void OnxuenianChanged();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    #endregion
		
		public Reward_Punish()
		{
			OnCreated();
		}
		
		[Column(Storage="_studengID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string studengID
		{
			get
			{
				return this._studengID;
			}
			set
			{
				if ((this._studengID != value))
				{
					this.OnstudengIDChanging(value);
					this.SendPropertyChanging();
					this._studengID = value;
					this.SendPropertyChanged("studengID");
					this.OnstudengIDChanged();
				}
			}
		}
		
		[Column(Storage="_rewards", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string rewards
		{
			get
			{
				return this._rewards;
			}
			set
			{
				if ((this._rewards != value))
				{
					this.OnrewardsChanging(value);
					this.SendPropertyChanging();
					this._rewards = value;
					this.SendPropertyChanged("rewards");
					this.OnrewardsChanged();
				}
			}
		}
		
		[Column(Storage="_punishments", DbType="VarChar(50)")]
		public string punishments
		{
			get
			{
				return this._punishments;
			}
			set
			{
				if ((this._punishments != value))
				{
					this.OnpunishmentsChanging(value);
					this.SendPropertyChanging();
					this._punishments = value;
					this.SendPropertyChanged("punishments");
					this.OnpunishmentsChanged();
				}
			}
		}
		
		[Column(Storage="_xuenian", DbType="VarChar(50)")]
		public string xuenian
		{
			get
			{
				return this._xuenian;
			}
			set
			{
				if ((this._xuenian != value))
				{
					this.OnxuenianChanging(value);
					this.SendPropertyChanging();
					this._xuenian = value;
					this.SendPropertyChanged("xuenian");
					this.OnxuenianChanged();
				}
			}
		}
		
		[Column(Storage="_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.School_fee")]
	public partial class School_fee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Xuenian;
		
		private string _Yingjiaoxuefei;
		
		private string _Yijiaoxuefei;
		
		private string _Qianjiaoxuefei;
		
		private string _Yingjiaozhusufei;
		
		private string _Yijiaozhusufei;
		
		private string _Qianjiaozhusufei;
		
		private string _studentID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnXuenianChanging(string value);
    partial void OnXuenianChanged();
    partial void OnYingjiaoxuefeiChanging(string value);
    partial void OnYingjiaoxuefeiChanged();
    partial void OnYijiaoxuefeiChanging(string value);
    partial void OnYijiaoxuefeiChanged();
    partial void OnQianjiaoxuefeiChanging(string value);
    partial void OnQianjiaoxuefeiChanged();
    partial void OnYingjiaozhusufeiChanging(string value);
    partial void OnYingjiaozhusufeiChanged();
    partial void OnYijiaozhusufeiChanging(string value);
    partial void OnYijiaozhusufeiChanged();
    partial void OnQianjiaozhusufeiChanging(string value);
    partial void OnQianjiaozhusufeiChanged();
    partial void OnstudentIDChanging(string value);
    partial void OnstudentIDChanged();
    #endregion
		
		public School_fee()
		{
			OnCreated();
		}
		
		[Column(Storage="_Xuenian", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string Xuenian
		{
			get
			{
				return this._Xuenian;
			}
			set
			{
				if ((this._Xuenian != value))
				{
					this.OnXuenianChanging(value);
					this.SendPropertyChanging();
					this._Xuenian = value;
					this.SendPropertyChanged("Xuenian");
					this.OnXuenianChanged();
				}
			}
		}
		
		[Column(Storage="_Yingjiaoxuefei", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Yingjiaoxuefei
		{
			get
			{
				return this._Yingjiaoxuefei;
			}
			set
			{
				if ((this._Yingjiaoxuefei != value))
				{
					this.OnYingjiaoxuefeiChanging(value);
					this.SendPropertyChanging();
					this._Yingjiaoxuefei = value;
					this.SendPropertyChanged("Yingjiaoxuefei");
					this.OnYingjiaoxuefeiChanged();
				}
			}
		}
		
		[Column(Storage="_Yijiaoxuefei", DbType="VarChar(50)")]
		public string Yijiaoxuefei
		{
			get
			{
				return this._Yijiaoxuefei;
			}
			set
			{
				if ((this._Yijiaoxuefei != value))
				{
					this.OnYijiaoxuefeiChanging(value);
					this.SendPropertyChanging();
					this._Yijiaoxuefei = value;
					this.SendPropertyChanged("Yijiaoxuefei");
					this.OnYijiaoxuefeiChanged();
				}
			}
		}
		
		[Column(Storage="_Qianjiaoxuefei", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Qianjiaoxuefei
		{
			get
			{
				return this._Qianjiaoxuefei;
			}
			set
			{
				if ((this._Qianjiaoxuefei != value))
				{
					this.OnQianjiaoxuefeiChanging(value);
					this.SendPropertyChanging();
					this._Qianjiaoxuefei = value;
					this.SendPropertyChanged("Qianjiaoxuefei");
					this.OnQianjiaoxuefeiChanged();
				}
			}
		}
		
		[Column(Storage="_Yingjiaozhusufei", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Yingjiaozhusufei
		{
			get
			{
				return this._Yingjiaozhusufei;
			}
			set
			{
				if ((this._Yingjiaozhusufei != value))
				{
					this.OnYingjiaozhusufeiChanging(value);
					this.SendPropertyChanging();
					this._Yingjiaozhusufei = value;
					this.SendPropertyChanged("Yingjiaozhusufei");
					this.OnYingjiaozhusufeiChanged();
				}
			}
		}
		
		[Column(Storage="_Yijiaozhusufei", DbType="VarChar(50)")]
		public string Yijiaozhusufei
		{
			get
			{
				return this._Yijiaozhusufei;
			}
			set
			{
				if ((this._Yijiaozhusufei != value))
				{
					this.OnYijiaozhusufeiChanging(value);
					this.SendPropertyChanging();
					this._Yijiaozhusufei = value;
					this.SendPropertyChanged("Yijiaozhusufei");
					this.OnYijiaozhusufeiChanged();
				}
			}
		}
		
		[Column(Storage="_Qianjiaozhusufei", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Qianjiaozhusufei
		{
			get
			{
				return this._Qianjiaozhusufei;
			}
			set
			{
				if ((this._Qianjiaozhusufei != value))
				{
					this.OnQianjiaozhusufeiChanging(value);
					this.SendPropertyChanging();
					this._Qianjiaozhusufei = value;
					this.SendPropertyChanged("Qianjiaozhusufei");
					this.OnQianjiaozhusufeiChanged();
				}
			}
		}
		
		[Column(Storage="_studentID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string studentID
		{
			get
			{
				return this._studentID;
			}
			set
			{
				if ((this._studentID != value))
				{
					this.OnstudentIDChanging(value);
					this.SendPropertyChanging();
					this._studentID = value;
					this.SendPropertyChanged("studentID");
					this.OnstudentIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
